2018-04-23 01:38:41,156 ERROR: Exception on /user/semd [GET] [in /home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jeditelo/flask/flask/app/routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jeditelo/flask/flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jeditelo/flask/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/jeditelo/flask/flask/app/templates/user.html", line 21, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
2018-04-23 01:39:22,208 INFO: Microblog startup [in /home/jeditelo/flask/flask/app/__init__.py:40]
2018-04-23 01:39:27,193 ERROR: Exception on /user/semd [GET] [in /home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jeditelo/flask/flask/app/routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jeditelo/flask/flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jeditelo/flask/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/jeditelo/flask/flask/app/templates/user.html", line 21, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/jeditelo/flask/flask/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
2018-04-23 01:47:09,458 INFO: Microblog startup [in /home/jeditelo/flask/flask/app/__init__.py:40]
